#server:
#  port: 8082
#
#spring:
#  application:
#    name: notification-service
#
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
#
#  rabbitmq:
#    host: ${RABBIT_HOST}
#    port: ${RABBIT_PORT}
#    username: ${RABBIT_USERNAME}
#    password: ${RABBIT_PASSWORD}
#
#  redis:
#    host: ${REDIS_HOST}
#    port: ${REDIS_PORT}
#
#  mail:
#    host: ${MAIL_HOST}
#    port: ${MAIL_PORT}
#    username: ${MAIL_USERNAME}
#    password: ${MAIL_PASSWORD}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#
#swagger:
#  base-package: com.notificationservice
#  title: Notification Service API
#  description: Handles email notifications
#  version: 1.0
#
#springfox:
#  documentation:
#    swagger:
#      v2:
#        path: /v2/api-docs
#
#logging:
#  level:
#    root: INFO
#    org.springframework: INFO
#    org.springframework.amqp.support.converter: DEBUG
#    com.notificationservice: DEBUG



server:
  port: 8082

spring:
  application:
    name: notification-service

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  redis:
    host: localhost
    port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: naveen.enjamuri22902@gmail.com
    password: ytea rgbn ydhj rxpj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


swagger:
  base-package: com.notificationservice
  title: Notification Service API
  description: Handles email notifications
  version: 1.0

# ✅ Logging (Optional but helpful)
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.amqp.support.converter: DEBUG
    com.notificationservice: DEBUG

# ✅ Enable Swagger
springfox:
  documentation:
    swagger:
      v2:
        path: /v2/api-docs


#spring:
  main:
    allow-bean-definition-overriding: true











#server:
#  port: 8082
#
#spring:
#  application:
#    name: notification-service
#
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: naveen.enjamuri22902@gmail.com
#    password: ytea rgbn ydhj rxpj
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#
#
#
##server:
##  port: 8082
##
##spring:
##  application:
##    name: notification-service
##
##  mail:
##    host: smtp.gmail.com
##    port: 587
##    username: your.email@gmail.com
##    password: your-app-password
##    properties:
##      mail.smtp.auth: true
##      mail.smtp.starttls.enable: true
##
##rabbitmq:
##  queue: notification-queue
##  exchange: notification-exchange
##  routingKey: notification-routing-key
##
##spring.rabbitmq:
##  host: localhost
##  port: 5672
##  username: guest
##  password: guest
