#name: CI Workflow
#
#on:
#  push:
#    branches: [ main ]
#
#jobs:
#  build:
#
#    runs-on: ubuntu-latest
#
#    services:
#      rabbitmq:
#        image: rabbitmq:3-management
#        ports:
#          - 5672:5672
#          - 15672:15672
#      redis:
#        image: redis:alpine
#        ports:
#          - 6379:6379
#
#    steps:
#      - name: Checkout Code
#        uses: actions/checkout@v3
#
#      - name: Set up Java
#        uses: actions/setup-java@v3
#        with:
#          java-version: '8'
#          distribution: 'adopt'
#
#      - name: Build with Maven
#        run: mvn clean install
#
#      - name: Docker Build & Tag
#        run: |
#          docker build -t user-service ./user-service
#          docker build -t notification-service ./notification-service
#
#
















##// Placeholder for ci.yml
#
#name: Build and Test UserManagement
#
#on:
#  push:
#    branches: [main]
#  pull_request:
#    branches: [main]
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    services:
#      mysql:
#        image: mysql:5.7
#        env:
#          MYSQL_ROOT_PASSWORD: root
#          MYSQL_DATABASE: userdb
#        ports:
#          - 3306:3306
#      redis:
#        image: redis
#        ports:
#          - 6379:6379
#      rabbitmq:
#        image: rabbitmq:3-management
#        ports:
#          - 5672:5672
#          - 15672:15672
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Set up Java
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'temurin'
#          java-version: '8'
#
#      - name: Build with Maven
#        run: mvn clean install -DskipTests
